name: GNP elections update
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scrape:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: r-lib/actions/setup-r@v2
      - name: r Packages
        run: Rscript -e 'install.packages(c("rvest", "tidyverse", "stringr"))'
      - name: broom install
        run: Rscript -e 'install.packages("broom", type="binary")'
      - name: Run script
        run: Rscript notif_only.R
      - name: Results
        run: |
          git add -A
          git commit -m 'Data uploaded' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
